### ISSUE TITLE
No pom.xml file provided for PySpark dependencies example

### ISSUE THREAD

**Issue by alistairdivorty** [aws-samples/emr-serverless-samples#15]
Could the `pom.xml` file mentioned in the [README](https://github.com/aws-samples/emr-serverless-samples/blob/main/examples/pyspark/dependencies/README.md) for the PySpark dependencies example please be provided?

**Comment by dacort** [comment]
Thanks @alistairdivorty! 

Apologies for that - pushing the file momentarily. :)

**Comment by alistairdivorty** [comment]
Thank you @dacort!
